name: Deploy project JSON
on: 
  push:
    branches: main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ github.token }}
          fetch-depth: 0          
          
      - name: Get Version
        id: version
        uses: paulhatch/semantic-version@v5.0.2

      - name: Create JSON File
        id: create
        uses: ./.github/actions/create-json-file
        with:
          json-version: '${{ steps.version.outputs.version }}'

      - name: Checkout Page branch
        uses: actions/checkout@v3
        with:
          ref: page
          token: ${{ github.token }}
          fetch-depth: 0          

      - name: Write JSON File
        id: write
        uses: ./.github/actions/write-json-file
        with:
          data: '${{ steps.create.outputs.data }}'

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions 
          author_email: marcus@cuda.org
          tag: 'v${{ steps.version.outputs.version }}-json'
